-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 08:11:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructors` (
  `Instructor_id` INT NOT NULL AUTO_INCREMENT,
  `Instructor_name` VARCHAR(45) NULL,
  `Department_Depatment_id` INT NOT NULL,
  PRIMARY KEY (`Instructor_id`),
  INDEX `fk_Instructors_Department1_idx` (`Department_Depatment_id` ASC),
  CONSTRAINT `fk_Instructors_Department1`
    FOREIGN KEY (`Department_Depatment_id`)
    REFERENCES `mydb`.`Department` (`Depatment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Head`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Head` (
  `Head_id` INT NOT NULL AUTO_INCREMENT,
  `Head_name` VARCHAR(45) NOT NULL,
  `Instructors_Instructor_id` INT NOT NULL,
  PRIMARY KEY (`Head_id`),
  UNIQUE INDEX `Head_name_UNIQUE` (`Head_name` ASC),
  INDEX `fk_Head_Instructors1_idx` (`Instructors_Instructor_id` ASC),
  CONSTRAINT `fk_Head_Instructors1`
    FOREIGN KEY (`Instructors_Instructor_id`)
    REFERENCES `mydb`.`Instructors` (`Instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Depatment_id` INT NOT NULL AUTO_INCREMENT,
  `Department_name` VARCHAR(45) NULL,
  `Head_Head_id` INT NOT NULL,
  PRIMARY KEY (`Depatment_id`),
  INDEX `fk_Department_Head1_idx` (`Head_Head_id` ASC),
  CONSTRAINT `fk_Department_Head1`
    FOREIGN KEY (`Head_Head_id`)
    REFERENCES `mydb`.`Head` (`Head_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `Course_id` INT NOT NULL AUTO_INCREMENT,
  `Department_Depatment_id` INT NOT NULL,
  `Course_name` VARCHAR(45) NULL,
  `Instructors_Instructor_id` INT NOT NULL,
  PRIMARY KEY (`Course_id`),
  INDEX `fk_Course_Department_idx` (`Department_Depatment_id` ASC),
  INDEX `fk_Course_Instructors1_idx` (`Instructors_Instructor_id` ASC),
  CONSTRAINT `fk_Course_Department`
    FOREIGN KEY (`Department_Depatment_id`)
    REFERENCES `mydb`.`Department` (`Depatment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Instructors1`
    FOREIGN KEY (`Instructors_Instructor_id`)
    REFERENCES `mydb`.`Instructors` (`Instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `Student_id` INT NOT NULL AUTO_INCREMENT,
  `Student_name` VARCHAR(45) NOT NULL,
  `Student_Age` VARCHAR(45) NOT NULL,
  `Student_Address` VARCHAR(45) NULL,
  `Student_scores` INT NOT NULL,
  PRIMARY KEY (`Student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Course` (
  `Students_Student_id` INT NOT NULL,
  `Course_Course_id` INT NOT NULL,
  PRIMARY KEY (`Students_Student_id`, `Course_Course_id`),
  INDEX `fk_Students_has_Course_Course1_idx` (`Course_Course_id` ASC),
  INDEX `fk_Students_has_Course_Students1_idx` (`Students_Student_id` ASC),
  CONSTRAINT `fk_Students_has_Course_Students1`
    FOREIGN KEY (`Students_Student_id`)
    REFERENCES `mydb`.`Students` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Course_Course1`
    FOREIGN KEY (`Course_Course_id`)
    REFERENCES `mydb`.`Course` (`Course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
